services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
